version: '3.7'
services:
  free-unity-mat-service:
    build: .
    container_name: free-unity-mat-con
    environment:
      XDEBUG_SESSION: "PHPSTORM"
    volumes:
      - ./dist:/var/www/html/dist
    ports:
      - "80:80"
  phpmyadmin:
    container_name: fum-admin
    image: phpmyadmin
    depends_on:
      - fum-db-service
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=fum-db-service
      - PMA_PORT:3306
  fum-server:
    build: .
    container_name: fum-server
    volumes:
      - ./server:/var/www/html/server
    ports:
      - "8000:8000"
  fum-db-service:
    build: .
    container_name: fum-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "PrimaryDatabase"
    ports:
      - "9906:3306"
networks:
  default:
    external:
      name: free-unity-mat-network
      #docker network create free-unity-mat-network

#sudo docker exec -t -i fum-db /bin/bash

#sudo docker exec -t -i fum-server /bin/bash

#sudo docker exec -t -i fum-admin /bin/bash

#sudo docker exec -t -i free-unity-mat-con /bin/bash