version: '3.7'
services:
  fum-service:
    #by default names are generated like projectname_servicename_number
    container_name: fum-service
    build:
      context: .
      dockerfile: ./dockerfiles/frontend/Dockerfile
    tty: true
    restart: always
    volumes:
      - ./dist:/var/www/html/dist
    environment:
      XDEBUG_SESSION: "PHPSTORM"
    ports:
      - "80:80"
    networks:
      - fumnet
  phpmyadmin:
    container_name: phpmyadmin
    restart: always
    image: phpmyadmin/phpmyadmin
    depends_on:
      - fum-db
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=fum-db
      - PMA_PORT=3306
    networks:
      - fumnet
  fum-server:
    container_name: fum-server
    build:
      context: .
      dockerfile: ./dockerfiles/server/Dockerfile
    tty: true
    restart: always
    volumes:
      - ./server:/var/www/html/server
    ports:
      - "8000:8000"
    networks:
      - fumnet
  fum-db:
    container_name: fum-db
    build:
      context: .
      dockerfile: ./dockerfiles/database/Dockerfile
    tty: true
    restart: always
    #TODO: try use this to start mysql entrypoint: service mysql start
    ports:
      - "9906:3306"
    volumes:
      - db:/var/lib/mysql
    networks:
      - fumnet
volumes:
  db:
networks:
  fumnet:
    name: fumnet
    external: true