version: '3.7'
services:
  fum-service:
    #by default names are generated like projectname_servicename_number
    container_name: fum-service
    build:
      context: .
      dockerfile: ./dockerfiles/frontend/Dockerfile
    tty: true
    volumes:
      - ./dist:/var/www/html/dist
    environment:
      XDEBUG_SESSION: "PHPSTORM"
    ports:
      - "80:80"
  phpmyadmin:
    #container_name: phpmyadmin
    #build:
    #  context: .
    #  dockerfile: ./dockerfiles/phpmyadmin/Dockerfile
    tty: true
    image: phpmyadmin
    depends_on:
      - fum-db
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=fum-db
      - PMA_PORT:3306
  fum-server:
    container_name: fum-server
    build:
      context: .
      dockerfile: ./dockerfiles/server/Dockerfile
    tty: true
    volumes:
      - ./server:/var/www/html/server
    ports:
      - "8000:8000"
  fum-db:
    container_name: fum-db
    build:
      context: .
      dockerfile: ./dockerfiles/database/Dockerfile
    tty: true
    restart: always
    ports:
      - "9906:3306"
    volumes:
      - db:/var/lib/mysql
    expose:
      - "3306"
volumes:
  db: