version: '3.7'
services:
  free-unity-mat-service:
    build: .
    container_name: free-unity-mat-con
    environment:
      XDEBUG_SESSION: "PHPSTORM"
    volumes:
      - ./dist:/var/www/html/dist
    ports:
      - "80:80"
  phpmyadmin:
    container_name: fum-admin
    image: phpmyadmin
    restart: always
    depends_on:
      - fum-db-service
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=fum-db-service
  fum-server:
    build: .
    container_name: fum-server
    restart: always
    environment:
      XDEBUG_SESSION: "PHPSTORM"
    volumes:
      - ./server:/var/www/html/server
    ports:
      - "8000:80"
  fum-db-service:
    build: .
    container_name: fum-db
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "PrimaryDatabase"
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "admin"
    ports:
      - "9906:3306"
    volumes:
      - dbdata:/var/lib/mysql
volumes:
  dbdata:
networks:
  default:
    external:
      name: free-unity-mat-network
      #docker network create free-unity-mat-network